FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://ollama.com/install.sh | sh

COPY . .
ENV PYTHONPATH=/app
RUN pip install --no-cache-dir -r requirements.txt

CMD ["bash"]